# Generated by Django 5.1 on 2024-08-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Hobbie')),
                ('inicio', models.DateField(auto_now_add=True, verbose_name='Data Inicio')),
                ('descricao', models.TextField(max_length=150, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='hobbies', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesFavoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Series Favoritas')),
                ('inicio', models.DateField(auto_now_add=True, verbose_name='Data de inicio')),
                ('descricao', models.TextField(max_length=150, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='series', verbose_name='Imagem')),
            ],
        ),
    ]
