# Generated by Django 5.1 on 2024-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passatempos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Passatempos')),
                ('inicio', models.DateField(auto_now_add=True, verbose_name='Data de inicio')),
                ('descricao', models.TextField(max_length=150, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='passatempos', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Profissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Profissão')),
                ('inicio', models.DateField(auto_now_add=True, verbose_name='Data Inicio')),
                ('descricao', models.TextField(max_length=150, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='profissoes', verbose_name='Imagem')),
            ],
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
        migrations.DeleteModel(
            name='SeriesFavoritas',
        ),
    ]
